### ISSUE TITLE
could you provide dragon data for test？

### ISSUE THREAD

**Issue by ForrestPi** [Kai-46/IRON#1]
`. ./train_scene.sh drv/dragon`
got Error
FileNotFoundError: [Errno 2] No such file or directory: './data_flashlight/drv/dragon/train/cam_dict_norm.json'

**Comment by endlesswho** [comment]
@Kai-46 the download_data.sh you provide is llff datasets not your drv/dragon datasets.

**Comment by ForrestPi** [comment]
@Kai-46  how to set the dataset for train and test ?

**Comment by Kai-46** [comment]
Sorry but the data release is on the way. We have some logistic issues to figure out before making the data public, as we don't own the data.

**Comment by EricStuart** [comment]
I use imgs from LLFF and the "cam_dict_norm.json" extracted by your previous repo nerfplusplus then train it, But the val result is empty，an empty normal.jpg and mesh.ply, where the problem might be?

**Comment by Kai-46** [comment]
Sorry for the delay. Please check the `download_data.sh` script again for data. Please do not use LLFF data.

**Comment by wirstrom** [comment]
Hi,
could you please explain all the steps I need to do to be able to run `. ./train_scene.sh drv/dragon` as specified in the `README.md`

### EDIT
I managed to train the `Luan et al 2021/xmen/` dataset. I only had to modify `train_scene.sh` by changing all the `--data_dir` from `--data_dir ./data_flashlight/${SCENE}/train` to `--data_dir "${SCENE}/train"`. Then I could run 

    . ./train_scene.sh  Luan_et_al_2021/xmen/

Note that removing spaces in the directory names is important.
