### ISSUE TITLE
About photometric image

### ISSUE THREAD

**Issue by menyifang** [Kai-46/IRON#12]
Awesome work! Is this method only valid for photometric images (captured by a hand-held smartphone camera with LED flashlight turned on in a dark environment)? Can we use images captured by a phone in a common indoor scene?

**Comment by Kai-46** [comment]
Yes, this codebase only expects photometric images, as we have hard-coded a point-light-based renderer: https://github.com/Kai-46/IRON/blob/8e9a7c172542afd52b8e6ef28bc96ad52b5ffd5a/models/renderer_ggx.py#L15

**Comment by menyifang** [comment]
Thanks for the reply. Do you have any idea how to extend it to common capture scenes?

**Comment by Kai-46** [comment]
Inverse rendering with natural envmap lighting is a very challenging problem. Usually in literature, people make simplified assumptions to make this problem more tractable, for example: 1) model direct illumination only: [PhySG](https://github.com/Kai-46/PhySG), [nvdiffrec](https://github.com/NVlabs/nvdiffrec); 2) fixed geometry: [NeILF](https://arxiv.org/abs/2203.07182), [InvRender](https://github.com/zju3dv/invrender). These simplified assumptions sacrifices quality though. The good thing with photometric images is that lighting are controlled to minimize shadows in captured images, and to simplify the evaluation of rendering equation.

**Comment by menyifang** [comment]
Thanks for the cues! help a lot
