### ISSUE TITLE
About BRDF

### ISSUE THREAD

**Issue by Woolseyyy** [Kai-46/IRON#13]
Hi, Kai!
I read the code and am confused about the BRDF implemented. According to the [code](https://github.com/Kai-46/IRON/blob/main/models/renderer_ggx.py#L69) , `specular_rgb = light_intensity * specular_albedo * F * D * G / (4.0 * dot + 1e-10)` and `F = 0.03867`, the F is fixed and a 'specular_albedo' is multiplied in BRDF, which is different from simplified Disney BSDF used in PhySG.  Could you introduce which BRDF you used?
Thank you!

**Comment by Kai-46** [comment]
It's the roughplastic BRDF in Mitsuba; see section 8.2.9 in this pdf: https://www.mitsuba-renderer.org/releases/current/documentation.pdf . However, one can also switch to the simplified Disney BRDF as in PhySG; it's on our development roadmap, but I haven't got time to implement it yet.

**Comment by Woolseyyy** [comment]
I see. In many other related papers, I notice that there are usually some prio assumption about the brdf function or brdf parameters according to the target material. Is it very difficult to overcome the ambiguity to learn brdf parameters of various materials?  Would you like to share your knowldge and experience about it?

**Comment by Kai-46** [comment]
Usually, plastic and metal materials can be modelled by the same class of parametric BRDF, e.g., disney BRDF; and these are probably the most common materials in literature. Inverse rendering with general materials is still an open problem, I think.

**Comment by Woolseyyy** [comment]
I see. Thank you!
