### ISSUE TITLE
About GGX Renderer

### ISSUE THREAD

**Issue by changfali** [Kai-46/IRON#18]
Hi，
I read the code and am confused about the BRDF implemented. Why the diffuse_rgb is compute like this:https://github.com/Kai-46/IRON/blob/8e9a7c172542afd52b8e6ef28bc96ad52b5ffd5a/models/renderer_ggx.py#L105, but not: light_intensity * (diffuse_albedo / np.pi) ? Could you introduce the meaning of other variables you used(Fdr, T12, T21, m_invEta2)? If the light and camera are not colocated, how to get the T21, T12?

**Comment by Kai-46** [comment]
These equations are what we inherit from the Mistuba renderer. Please refer to MIstuba `roughplastic `BRDF for details.
