### ISSUE TITLE
Why should we use  "roughness range loss"

### ISSUE THREAD

**Issue by Woolseyyy** [Kai-46/IRON#4]
Hi Kai,
Appreciate for your another great work! The results of IRON look amazing! 
However, I am confused about the "roughness range loss" mentioned in the paper. Why should we encourage the estimated roughness to stay below 0.5? What if we meet object with large roughness in custom data? 
Looking forward to your advice.

**Comment by Kai-46** [comment]
The Mitsuba` roughplastic `BRDF model we are using is already pretty diffuse when roughness=0.5; hence we thought it might be better to constrain the values to be below 0.5.

**Comment by Woolseyyy** [comment]
Got it! Thank you!
