### ISSUE TITLE
Blender Error: File format is not supported in file 'mesh.obj'

### ISSUE THREAD

**Issue by endlesswho** [Kai-46/IRON#6]
Finished importing: './exp_iron_stage2/superman/mesh_and_materials_10000/mesh.obj'
Progress: 100.00%

    (  0.0002 sec |   0.0000 sec) OBJ Export path: './exp_iron_stage2/superman/mesh_and_materials_10000/mesh.obj'
          ( 93.8459 sec |  93.8253 sec) Finished writing geometry of 'mesh'.
      ( 93.8462 sec |  93.8459 sec) Finished exporting geometry, now exporting materials
      ( 93.8462 sec |  93.8460 sec) OBJ Export Finished
Progress: 100.00%

Error: File format is not supported in file '/IRON/exp_iron_stage2/superman/mesh_and_materials_10000/mesh.obj'

Blender quit
ic| 'Exporting materials...'
Warning: readOBJ() ignored non-comment line 3:

**Comment by endlesswho** [comment]
> Obj files are just text files, which you could view using text editors like vim. Can you please paste a screenshot of the lines causing errors for me to inspect?

the obj file before run blender script:
`# https://github.com/mikedh/trimesh
v 0.32813224 0.29395986 0.15218830
v 0.32809478 0.29404968 0.15217558
v 0.32830498 0.29396206 0.15166572
v 0.32785499 0.29395503 0.15300721
v 0.32777151 0.29415402 0.15297887
v 0.32757002 0.29394838 0.15382323
v 0.32745698 0.29421705 0.15378484
v 0.32727689 0.29393980 0.15463623
v 0.32715160 0.29423657 0.15459365`
after I run the blender script
![image](https://user-images.githubusercontent.com/8555404/178394961-5de4bf9f-18f4-477d-affe-cba4fd8600ef.png)

**Comment by Kai-46** [comment]
Sorry I'm confused. Were you trying to say that blender failed to write a mesh with correct UV or blender failed to write a mesh at all?

**Comment by endlesswho** [comment]
> Sorry I'm confused. Were you trying to say that blender failed to write a mesh with correct UV or blender failed to write a mesh at all?

Sorry for my disturb, It seems this error doesn't cause the pipline.

**Comment by CCOSerika** [comment]
I met the same problem. I got the .obj and .mtl file, but blender didn't show the result correctly. I want to konw how to show the model with materials in blender. Thanx in advance.

**Comment by linglichen** [comment]
> I met the same problem. I got the .obj and .mtl file, but blender didn't show the result correctly. I want to konw how to show the model with materials in blender. Thanx in advance.

I also met the same problem, did you solve it？
