### ISSUE TITLE
I use the default config, but the reault is too bad

### ISSUE THREAD

**Issue by silence401** [Kai-46/IRON#7]
Thanks for your excellent work!
I use the xmen data you provoided, but the result is worse than the paper said. 
The test_result as follow:
![image](https://user-images.githubusercontent.com/29566012/179126388-0115edda-9e64-49ff-91d6-5312c0bfdb8e.png)

And the result of superman:
![image](https://user-images.githubusercontent.com/29566012/179156207-49f1b316-5a0f-43f1-a409-72d1bc24bcff.png)

**Comment by Kai-46** [comment]
Hi @silence401 , this is a significantly refactored version (for improved readability) of the private codebase I used for experiments; I haven't got time to carefully checked reproducibility yet. 

This said,  I did clone this public codebase, follow the steps on the readme, and re-run the experiment without hassles last night. Below are the test-set results I got for the xmen:

<img width="837" alt="image" src="https://user-images.githubusercontent.com/21653654/179227417-9708ce2e-1611-4d48-a2b9-3d5ac6067563.png">

I'm not sure what happened on your side based on this limited information; can you try spending some time debugging this issue first?
