### ISSUE TITLE
Learning Specular and Roughness fails and produces a strange phenomenon

### ISSUE THREAD

**Issue by HaldonFu** [Kai-46/IRON#8]
Thanks for your excellent work!
I use the duck data from phySG you provoided, and I used the mask *.png in stage1, mask_weight=100.0,  but the result of the stage2 is incorrect.  
The logim result as follow:
![image](https://user-images.githubusercontent.com/97090205/180353448-e4e22938-1af9-41c7-8a44-c76168efd007.png)
Can you tell me where the problem might be?

**Comment by Kai-46** [comment]
This work assumes colocated flash lighting, rather than the envmap lighting as in PhySG.

**Comment by HaldonFu** [comment]
Thank you for your reply. I also want to ask how the results of duck or kitty in the synthetic_assets are obtained. Can you tell me?

**Comment by Kai-46** [comment]
You might want to take a closer look at the readme regarding synthetic data rendering with Mitsuba.

**Comment by HaldonFu** [comment]
Thank you for your reply! I want to know how to convert the envmap_lighting data as in PhySG into flashlight data, and how to get the mesh, diffuse/specular albedo and roughness like in synthetic_assets? Can you tell me?

**Comment by Woolseyyy** [comment]
Hi, @Kai-46 ! I also want to ask for the mesh and albedo of synthetic_assets mentioned in PhySG. 
I searched for a long time and read the cited paper "Sparse-as-possible svbrdf acquisition", but still cannot find the raw mesh and diffuse albedo. I only find reconstructed data with bad quality from the project page of "Sparse-as-possible svbrdf acquisition".

**Comment by Kai-46** [comment]
As far as I know, there is no way to convert images with envmap lighting into images with flash lighting. You would have to re-render using Mistuba.
