### ISSUE TITLE
About preprocessing pipeline

### ISSUE THREAD

**Issue by Bingrong89** [Kai-46/IRON#9]
Hello! I tried to run IRON on my own dataset however it is not producing any viable results.
I assumed you were using NeRF++ for producing the cam_dict_norm.json, however there is very little detail on exactly how you processed the images obtained from camera.
Could you provide more details on the steps you took to process the images to create the train/test folders?

**Comment by Kai-46** [comment]
Can you attach the epipolar line visualization, as well as camera and point cloud visualization as in NeRF++ here for your data? 

Nothing special was done to the images; the images were captured by an iPhone, and then randomly split into train/test splits.

**Comment by Bingrong89** [comment]
![cam_vis_doraemon](https://user-images.githubusercontent.com/43532121/182071555-f00cafff-3121-4165-a835-3b1631f1c350.png)
![epipolar_doraemon](https://user-images.githubusercontent.com/43532121/182071567-a55b43ee-65bc-4f3f-80ea-23b804d27195.png)
This is the epipolar line visualization and camera visualization from my own dataset.
![snapshot00](https://user-images.githubusercontent.com/43532121/182071615-85af3240-46ca-4c3f-a135-c280e3a1d572.png)
This is the output i got from IRON.

![cam_vis_buddhahead](https://user-images.githubusercontent.com/43532121/182071763-be62ffb5-81e0-4252-8d98-8233df36af78.png)
![epipolar_buddhahead](https://user-images.githubusercontent.com/43532121/182071772-15148720-569f-4e1c-a31f-43b31de5f42c.png)
I also ran the same for buddha head, which I trained successfully on.
Note that for camera visualization, I used the mesh file and camera path file from Nerf++, I only changed the camera json files for train and test.

**Comment by Bingrong89** [comment]
Hi, sorry I think I figured out the problem? Colored background appearing in a number of the images used. Removed them and got a somewhat decent output, although I am still observing nan values in stage 2 training.

**Comment by changfali** [comment]
> Hello! I tried to run IRON on my own dataset however it is not producing any viable results. I assumed you were using NeRF++ for producing the cam_dict_norm.json, however there is very little detail on exactly how you processed the images obtained from camera. Could you provide more details on the steps you took to process the images to create the train/test folders?

Hi, 
I used the code "run_colmap.py" in Nerf++ to produce the cam_dict_norm.json, but the result was always bad, even for the given dataset. For example, for the given data, the steps I took is:

1. Used all the images in train/test to run the code "run_colmap.py";
2. Split the images in "xmen/mvs/image"(this is the result of "run_colmap.py") to train and test by myself
3. Used the json file: xmen/posed_images/kai_cameras_normalized.json to train Iron.

But the result of normal.png after 15000 iters was still bad:
![image](https://user-images.githubusercontent.com/68762767/185833851-dabb246c-20d2-45a1-be9e-436c34d98a43.png)
while for the original "Xmen" data, the normal.png result is always good even after 2500 iters. 

I'm a beginner in this field, and have been troubled by this problem for a long time, could you help me with it? Do you know which part could be wrong? @Kai-46 @Bingrong89

**Comment by changfali** [comment]
You can find more details in #15, That would be very great help for me!!
